### ISSUE TITLE
Group dependencies listed in lib.txt are not resolved

### ISSUE THREAD

**Issue by moshloop** [egis/gradle-build#1]
Given a local  **libs/lib.txt** with the following contents

```
commons-*.txt
commons-codec-123.jar
```

And **s3://${libBucket}/${libPrefix}** S3 folder containing:

```
commons-*.txt
commons-codec-123.jar
commons-io-123.jar
commons-bean.jar
```

And the contents of  **s3://${libBucket}/${libPrefix}/_commons-_.txt**

```
commons-io-123.jar
commons-bean.jar
```

Should be equiavalent to a **libs/lib.txt**  with these contents:

```
commons-io-123.jar
commons-bean.jar
commons-codec-123.jar
```

It should resolve `commons-*.txt` (or any other .txt file dependency) by first resolving that file  and resolving each line contained using the standard `{filename} {md5}` syntax.

**Comment by yegor256** [comment]
@Egis-Moshe this is the first ticket and repo we should start with, right?

**Comment by moshloop** [comment]
@yegor256 can we start on this?

**Comment by yegor256** [comment]
@Egis-Moshe I'm sure I understand how this should work. can you please reformat this ticket so that it sound like a bug? see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html What's important is to have a bug reproduction scenario.

**Comment by moshloop** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@Egis-Moshe it's better, but I still don't understand how can I reproduce it... what to run? where to look for results? what exactly means "resolve"?

**Comment by moshloop** [comment]
@yegor256 please checl update description and readme

**Comment by yegor256** [comment]
@Egis-Moshe a bit better, but still very vague... I can't understand what exactly "should be equivalent". Would be great if you use full English sentences, without making them shorter. Now all this sounds very cryptic.
